export enum CpeStatus {
  DRAFT = 'DRAFT',
  PENDING_AUTHORIZATION = 'PENDING_AUTHORIZATION',
  AUTHORIZED = 'AUTHORIZED',
  REJECTED = 'REJECTED',
  VOIDED = 'VOIDED',
  CONFIRMED = 'CONFIRMED',
  ERROR = 'ERROR',
}
