export enum EquipmentType {
  BARANDA_REBATIBLE = 'BARANDA_REBATIBLE',
  BARANDA_FIJA = 'BARANDA_FIJA',
  CISTERNA = 'CISTERNA',
  FURGON = 'FURGON',
  TOLVA = 'TOLVA',
  PLAYO = 'PLAYO',
  CARROZADO = 'CARROZADO',
  BATEA = 'BATEA',
  ESCALABLE = 'ESCALABLE',
  BITREN = 'BITREN',
}
