export enum IncidentType {
  ROTURA = 'ROTURA',
  PROBLEMA_MECANICO = 'PROBLEMA_MECANICO',
  DEMORA_PUERTO = 'DEMORA_PUERTO',
  ACCIDENTE = 'ACCIDENTE',
  CORTE_RUTA = 'CORTE_RUTA',
  INUNDACION = 'INUNDACION',
  TRANSITO_PESADO = 'TRANSITO_PESADO',
  OTRO = 'OTRO',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
