export enum TripAlertType {
  DEMORA_DESCARGA = 'DEMORA_DESCARGA',
  PROBLEMA_CALIDAD = 'PROBLEMA_CALIDAD',
  FALTA_DOCUMENTACION = 'FALTA_DOCUMENTACION',
  PROBLEMA_CARGA = 'PROBLEMA_CARGA',
  URGENCIA_CLIMA = 'URGENCIA_CLIMA',
  CAMBIO_TURNO = 'CAMBIO_TURNO',
  OTRO = 'OTRO',
}

export enum TripAlertPriority {
  NORMAL = 'NORMAL',
  URGENTE = 'URGENTE',
}

export enum TripAlertStatus {
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  CANCELLED = 'CANCELLED',
}
